theme: jekyll-theme-minimal
title: Chelsea Lord # your name (or website title) here
logo: "/images/headshot.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Neuroscientist | Transhumanist | Associate Neural Data Scientist | Mountain Biker | Backcountry Snowboarder
  <br>
  To get in touch, please reach out via <a href="https://www.linkedin.com/in/chelsea-lord-6b58901a8/">LinkedIn</a>
  <br>
  <br>
